### ISSUE TITLE
tileqa crashes for one backup tile 42957 (20230930)

### ISSUE THREAD

**Issue by abhi0395** [desihub/desisurveyops#146]
tileqa crashes to create tileqa.png for 42957 (backup tile on 20230930), citing following error:

```
CRITICAL:util.py:153:runcmd: FAILED rank 0 exception while running desispec.scripts.tileqa.main(['-g', 'cumulative', '-n', '20230930', '-t', '42957']) called from line 620 in /global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/zproc.py
ERROR:util.py:161:runcmd: Traceback (most recent call last):
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/util.py", line 144, in runcmd
    result = cmd(*args)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/tileqa.py", line 227, in main
    _wrap_make_tile_qa_plot(qafitsfile, specprod_dir=args.prod)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/tileqa.py", line 114, in _wrap_make_tile_qa_plot
    figfile = make_tile_qa_plot(qafitsfile, specprod_dir)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/tile_qa_plot.py", line 1276, in make_tile_qa_plot
    exps = get_expids_efftimes(tileqafits, prod)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/tile_qa_plot.py", line 967, in get_expids_efftimes
    d["QA_EFFTIME_SPEC"][i] = fits.getheader(fn, "FIBERQA")["EFFTIME"]
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/astropy/io/fits/header.py", line 169, in __getitem__
    card = self._cards[self._cardindex(key)]
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/astropy/io/fits/header.py", line 1819, in _cardindex
    raise KeyError(f"Keyword {keyword!r} not found.")
ERROR:util.py:161:runcmd: KeyError: "Keyword 'EFFTIME' not found."
CRITICAL:util.py:170:runcmd: FAILED desispec.scripts.tileqa.main(['-g', 'cumulative', '-n', '20230930', '-t', '42957'])
================= End of Process 0 ======
```
The issue was also opened by @araichoor (https://github.com/desihub/desispec/issues/2095), but it's not resolved yet. 

some digging shows:
```
from desispec.tile_qa_plot import get_expids_efftimes
get_expids_efftimes('/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/42957/20230930/tile-qa-42957-thru20230930.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/')
(Pdb) fn = '/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220112/00118314/exposure-qa-00118314.fits'
(Pdb) fits.getheader(fn, "FIBERQA")["EFFTIME"]
KeyError: "Keyword 'EFFTIME' not found."
fitsheader -e FIBERQA -k EFFTIME /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220112/00118314/exposure-qa-00118314.fits
WARNING: /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220112/00118314/exposure-qa-00118314.fits (HDU FIBERQA): Keyword EFFTIME not found. [[astropy.io](http://astropy.io/).fits.scripts.fitsheader]
# HDU FIBERQA in /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220112/00118314/exposure-qa-00118314.fits:
```

**Comment by schlafly** [comment]
It's not a big deal, but this seems like an internal desispec issue rather than a data quality / QA issue, so I think we would normally track it on desispec rather than on desisurveyops.  FWIW I do not know immediately what would lead EFFTIME to not get populated by desispec.

**Comment by schlafly** [comment]
This is being tracked on the desispec side; it relates to processing of tiles with early exposures from before we fixed this issue.  Closing here.
